# Generated by Django 4.2.30 on 2026-10-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPROVAL_REQUIRED', 'Approval Required'), ('BID_DEADLINE', 'Bid Window Closing'), ('EXCEPTION_RAISED', '3-Way Match Exception'), ('CONTRACT_EXPIRATION', 'Contract Expiration Warning'), ('PO_ACKNOWLEDGED', 'PO Acknowledged'), ('RFQ_INVITATION', 'New RFQ/RFP Invitation'), ('CLARIFICATION_RESPONSE', 'Clarification Response'), ('BID_SUBMITTED', 'Bid Submission Confirmation'), ('BID_AMENDED', 'Bid Amendment Confirmation'), ('PO_ISSUED', 'Purchase Order Issued'), ('PO_AMENDMENT', 'PO Amendment Notification'), ('KYC_REQUEST', 'KYC / Compliance Notification')], max_length=50),
        ),
    ]
