# Generated by Django 4.2.30 on 2026-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("APPROVAL_REQUIRED", "Approval Required"),
                    ("BID_DEADLINE", "Bid Window Closing"),
                    ("EXCEPTION_RAISED", "3-Way Match Exception"),
                    ("CONTRACT_EXPIRATION", "Contract Expiration Warning"),
                    ("CONTRACT_MILESTONE", "Contract Milestone Due Warning"),
                    ("CONTRACT_OBLIGATION", "Contract Obligation Due Warning"),
                    ("PO_ACKNOWLEDGED", "PO Acknowledged"),
                    ("RFQ_INVITATION", "New RFQ/RFP Invitation"),
                    ("CLARIFICATION_RESPONSE", "Clarification Response"),
                    ("BID_SUBMITTED", "Bid Submission Confirmation"),
                    ("BID_AMENDED", "Bid Amendment Confirmation"),
                    ("PO_ISSUED", "Purchase Order Issued"),
                    ("PO_AMENDMENT", "PO Amendment Notification"),
                    ("KYC_REQUEST", "KYC / Compliance Notification"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "is_read", "-created_at"], name="notif_recip_unread_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "-created_at"], name="notif_recip_created_idx"),
        ),
    ]
