# Generated by Django 4.2.19 on 2026-10-06 05:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0002_paymentstatus_matchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTolerancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one policy can be active at a time.')),
                ('price_tolerance_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='e.g. 0.0500 for 5%', max_digits=5)),
                ('qty_tolerance_pct', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='e.g. 0.0500 for 5%', max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
