# Generated by Django 4.2.30 on 2026-10-05 00:27

import apps.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcingevent',
            name='commercial_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sourcingevent',
            name='required_documents',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sourcingevent',
            name='technical_requirements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorbid',
            name='commercial_proposal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorbid',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbid',
            name='technical_proposal',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorbid',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendorbid',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AMENDED', 'Amended'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=30),
        ),
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Response'), ('ANSWERED', 'Answered')], default='PENDING', max_length=30)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='sourcing.sourcingevent')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='vendors.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technical_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('commercial_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('weighted_total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('comments', models.TextField(blank=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sourcing.vendorbid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='sourcing.sourcingevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('TECHNICAL', 'Technical Proposal Attachment'), ('COMMERCIAL', 'Commercial / Pricing Schedule'), ('COMPLIANCE', 'Compliance / Certification'), ('OTHER', 'Other Supporting Document')], default='TECHNICAL', max_length=50)),
                ('file', models.FileField(upload_to='bid_attachments/%Y/%m/', validators=[apps.core.validators.validate_file_upload])),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sourcing.vendorbid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BidVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('total_bid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('proposal_summary', models.TextField(blank=True, default='')),
                ('technical_proposal', models.TextField(blank=True, default='')),
                ('commercial_proposal', models.TextField(blank=True, default='')),
                ('amendment_reason', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='sourcing.vendorbid')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('bid', 'version_number')},
            },
        ),
    ]
