# Generated by Django 4.2.30 on 2026-10-06 10:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def mark_existing_awards_approved(apps, schema_editor):
    """Pre-existing AwardDecision rows were direct awards: mark them APPROVED."""
    AwardDecision = apps.get_model("sourcing", "AwardDecision")
    for decision in AwardDecision.objects.all():
        decision.status = "APPROVED"
        decision.recommended_by_id = decision.recommended_by_id or decision.approved_by_id
        decision.decided_at = decision.decided_at or decision.updated_at
        decision.save(update_fields=["status", "recommended_by", "decided_at"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sourcing", "0002_sourcingevent_commercial_requirements_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NegotiationNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="awarddecision",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="awarddecision",
            name="decision_comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="awarddecision",
            name="recommended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recommended_awards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="awarddecision",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bidevaluation",
            name="commercial_evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bidevaluation",
            name="technical_evaluated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcingevent",
            name="commercial_weight",
            field=models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=5),
        ),
        migrations.AddField(
            model_name="sourcingevent",
            name="technical_weight",
            field=models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=5),
        ),
        migrations.AlterField(
            model_name="awarddecision",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_awards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="awarddecision",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="award_decisions",
                to="sourcing.sourcingevent",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcingevent",
            index=models.Index(fields=["status", "bid_end_date"], name="sourcing_status_end_idx"),
        ),
        migrations.RunPython(mark_existing_awards_approved, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="awarddecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "APPROVED"])),
                fields=("event",),
                name="award_one_active_decision_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="bidevaluation",
            constraint=models.UniqueConstraint(
                fields=("bid", "evaluator"), name="evaluation_unique_per_bid"
            ),
        ),
        migrations.AddConstraint(
            model_name="bidevaluation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("technical_score__gte", 0),
                    ("technical_score__lte", 100),
                    ("commercial_score__gte", 0),
                    ("commercial_score__lte", 100),
                ),
                name="evaluation_scores_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcingevent",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("technical_weight__gte", 0),
                    ("commercial_weight__gte", 0),
                    ("technical_weight__lte", 100),
                    ("commercial_weight__lte", 100),
                ),
                name="sourcing_event_weights_range",
            ),
        ),
        migrations.AddField(
            model_name="negotiationnote",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="negotiation_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="negotiationnote",
            name="bid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiation_notes",
                to="sourcing.vendorbid",
            ),
        ),
        migrations.AddField(
            model_name="negotiationnote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="negotiationnote",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="negotiation_notes",
                to="sourcing.sourcingevent",
            ),
        ),
    ]
