# Generated by Django 4.2.30 on 2026-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorecards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendorscorecard",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="vendorscorecard",
            name="responsiveness_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100: RFQ invitation response rate and PO acknowledgement rate",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendorscorecard",
            name="sla_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100: vendor contract obligations fulfilled on/before due date",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorscorecard",
            name="compliance_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100 based on vendor KYC/governance status",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorscorecard",
            name="composite_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weighted score over available core indicators",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorscorecard",
            name="delivery_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100: share of GRNs received on/before the expected delivery date",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorscorecard",
            name="price_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100: invoiced value adherence to PO value (over-billing penalised)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendorscorecard",
            name="quality_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="0-100: accepted quantity / received quantity",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="vendorscorecard",
            index=models.Index(fields=["vendor", "created_at"], name="scorecard_vendor_ts_idx"),
        ),
    ]
