# Generated by Django 4.2.30 on 2026-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendorriskrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="vendorriskrecord",
            name="risk_flags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="vendorriskrecord",
            name="risk_level",
            field=models.CharField(
                choices=[("LOW", "Low Risk"), ("MEDIUM", "Medium Risk"), ("HIGH", "High Risk")],
                db_index=True,
                default="LOW",
                max_length=20,
            ),
        ),
    ]
