# Generated by Django 4.2.30 on 2026-10-05 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_pos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='acknowledgement_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_delivery_date', models.DateField()),
                ('quantity_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destination_address', models.TextField(blank=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_schedules', to='orders.purchaseorder')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='orders.poline')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
