# Generated by Django 4.2.30 on 2026-10-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_REVIEW', 'Manager Review'), ('BUDGET_REVIEW', 'Budget Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SOURCING', 'In Sourcing'), ('PO_ISSUED', 'PO Issued'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=50),
        ),
    ]
