# Generated by Django 4.2.30 on 2026-10-05 17:27

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("requisitions", "0002_alter_purchaserequisition_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="prattachment",
            name="file_size",
            field=models.PositiveIntegerField(default=0, help_text="File size in bytes"),
        ),
        migrations.AddField(
            model_name="prattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pr_attachments_uploaded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="prattachment",
            name="file",
            field=models.FileField(
                upload_to="pr_attachments/%Y/%m/",
                validators=[apps.core.validators.validate_pr_attachment],
            ),
        ),
    ]
